train_dataset:
  dataset:
    name: natl-sst
    args:
      root_path: /data/jean.legoff/data/RESAC-SARGAS60/data/natl60_htuv_01102012_01102013.npz
      repeat: 20
      cache: bin
  wrapper:
    name: ssh-sst-sr-implicit-downsampled
    args:
      inp_size: 16
      augment: true
      scale_min: 9
      scale_max: 9
      sample_q: 4608
  batch_size: 18
val_dataset:
  dataset:
    name: natl-sst
    args:
      root_path: /data/jean.legoff/data/RESAC-SARGAS60/data/natl60_htuv_03_06_09_12-2008.npz
      repeat: 20
      cache: bin
  wrapper:
    name: ssh-sst-sr-implicit-downsampled
    args:
      inp_size: 16
      scale_min: 9
      scale_max: 9
      sample_q: 4608
  batch_size: 18
model:
  name: jiif-unfold
  args:
    encoder_lr_spec:
      name: ssh-edsr-baseline
      args:
        no_upsampling: true
        n_feats: 128
    encoder_hr_spec:
      name: ssh-edsr-baseline
      args:
        no_upsampling: true
        n_feats: 128
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list:
        - 1024
        - 512
        - 256
        - 128
optimizer:
  name: adam
  args:
    lr: 0.0001
epoch_max: 500
epoch_val: 3
epoch_save: 10
data_norm:
  inp_sst:
    sub:
    - 24.383085250854492
    div:
    - 2.9732673168182373
  inp_ssh:
    sub:
    - 0.393464058637619
    div:
    - 0.3013797700405121
  gt:
    sub:
    - 0.396147221326828
    div:
    - 0.2945845425128937
