train_dataset:
  dataset:
    name: natl-sst
    args:
      root_path: /data/jean.legoff/data/RESAC-SARGAS60/data/natl60_htuv_01102012_01102013.npz
      repeat: 20
      cache: bin
  wrapper:
    name: ssh-sst-sr-implicit-downsampled
    args:
      inp_size: 16
      augment: true
      scale_min: 27
      scale_max: 27
      sample_q: 2304
  batch_size: 12
val_dataset:
  dataset:
    name: natl-sst
    args:
      root_path: /data/jean.legoff/data/RESAC-SARGAS60/data/natl60_htuv_03_06_09_12-2008.npz
      repeat: 20
      cache: bin
  wrapper:
    name: ssh-sst-sr-implicit-downsampled
    args:
      inp_size: 16
      scale_min: 27
      scale_max: 27
      sample_q: 2304
  batch_size: 12

model:
  name: jiif
  args:
    encoder_lr_spec:
      name: ssh-edsr-baseline
      args:
        no_upsampling: true
        n_feats: 128
    encoder_hr_spec:
      name: ssh-edsr-baseline
      args:
        no_upsampling: true
        n_feats: 128
    imnet_spec:
      name: mlp
      args:
        out_dim: 2
        hidden_list:
        - 1024
        - 512
        - 256
        - 128
optimizer:
  name: adam
  args:
    lr: 0.0001
epoch_max: 100
multi_step_lr:
  milestones:
  - 60
  gamma: 0.2
epoch_val: 2
epoch_save: 10
